version: '3.8'

services:
  ai-agent:
    build:
      context: ./agent
    container_name: ai_agent
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=AIzaSyCQ8goTqlpw_H39rLbiM1tyCvIZjeo-Xr4
    networks:
      - ai_net

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n.local
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - ai_net

volumes:
  n8n_data:

networks:
  ai_net:
